import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1C1C1F',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#E0E2E8',
        textDecorationLine: 'underline',
        textDecorationColor: '#5DA5B3',
        alignSelf: 'center',
        marginTop: 20,
        marginBottom: 20,
    },
    scrollViewContainer: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    searchButton: {
        backgroundColor: '#007bff',
        padding: 10,
        marginVertical: 10,
        borderRadius: 5,
        alignItems: 'center',
    },
    searchContainer: {
        backgroundColor: '#2C2C2E',
        borderRadius: 10,
        width: '90%',
        alignSelf: 'center',
        padding: 20,
    },
    rowContainer: {
        paddingLeft: 20,
        paddingRight: 20,
    },
    dateTimeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    halfInput: {
        width: '48%',
    },
    courseContainer: {
        backgroundColor: '#2C2C2E',
        borderRadius: 10,
        padding: 20,
        marginVertical: 10,
        borderWidth: 1,
        borderColor: '#5DA5B3',
    },
    courseName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#E0E2E8',
    },
    courseSchedule: {
        fontSize: 14,
        color: '#E0E2E8',
        marginBottom: 10,
    },
    courseTags: {
        fontSize: 14,
        color: '#E0E2E8',
        marginBottom: 10,
    },
    courseLink: {
        color: '#007bff',
        textDecorationLine: 'underline',
    },
    courseLinkTitle: {
        color: '#E0E2E8',
        marginRight: 10,
    },
    linkContainerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
    },
    modifyButton: {
        backgroundColor: '#007bff',
        padding: 10,
        marginTop: 10,
        borderRadius: 5,
        alignItems: 'center',
    },
    deleteButton: {
        backgroundColor: '#FF6347',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 15,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
        alignSelf: 'center',
    },
    createButton: {
        backgroundColor: '#007bff',
        padding: 15,
        borderRadius: 5,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: 'center',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#1C1C1F',
        padding: 20,
        borderRadius: 10,
        width: '80%',
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        color: '#E0E2E8',
    },
    input: {
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 10,
        padding: 10,
        borderRadius: 5,
        width: '100%',
        color: '#E0E2E8',
        backgroundColor: '#2C2C2F',
    },
    picker: {
        width: '90%',
        color: '#E0E2E8',
        marginBottom: 10,
    },
    pickerItem: {
        color: '#E0E2E8',
    },
    bottomContainer: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        alignItems: 'center',
        padding: 20,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#5DA5B3',
        padding: 15,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
        alignSelf: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
    },
    noOffersText: {
        fontSize: 16,
        color: '#E0E2E8',
        textAlign: 'center',
        marginVertical: 10,
    },
    cancelButton: {
        backgroundColor: '#6c757d',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 15,
        borderRadius: 5,
        marginTop: 10,
        width: '100%',
    },
    linkContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        justifyContent: 'space-between',
        width: '100%',
    },
    inputLink: {
        flex: 1,
        height: 40,
        borderColor: 'gray',
        borderWidth: 1,
        marginBottom: 10,
        padding: 10,
        borderRadius: 5,
        color: '#E0E2E8',
        backgroundColor: '#2C2C2F',
    },
    removeLinkButton: {
        color: '#FF6347',
        marginLeft: 10,
    },
});

export default styles;